server:
  port: 28080

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: demo

auth:
  ignore_urls:
    - "**/login"
    - "**/health"
  jwt:
    secret: "1qasrf45Xt6yh45tyhj6Q7yuikl89iolfty7"
    expiration_secs: 3600
    audience: "daoyi-cloud"
    issuer: "daoyi-cloud"
