
-- ----------------------------
-- Table structure for infra_api_access_log
-- ----------------------------
DROP TABLE IF EXISTS "infra_api_access_log";
CREATE TABLE "infra_api_access_log"
(
    "id"               bigint GENERATED BY DEFAULT AS IDENTITY,
    "trace_id"         varchar(64)  NOT NULL DEFAULT '',
    "user_id"          bigint       NOT NULL DEFAULT 0,
    "user_type"        smallint     NOT NULL DEFAULT 0,
    "application_name" varchar(50)  NOT NULL,
    "request_method"   varchar(16)  NOT NULL DEFAULT '',
    "request_url"      varchar(255) NOT NULL DEFAULT '',
    "request_params"   text         NULL,
    "response_body"    text         NULL,
    "user_ip"          varchar(50)  NOT NULL,
    "user_agent"       varchar(512) NOT NULL,
    "operate_module"   varchar(50)  NULL     DEFAULT NULL,
    "operate_name"     varchar(50)  NULL     DEFAULT NULL,
    "operate_type"     smallint     NULL     DEFAULT 0,
    "begin_time"       timestamp    NOT NULL,
    "end_time"         timestamp    NOT NULL,
    "duration"         integer      NOT NULL,
    "result_code"      integer      NOT NULL DEFAULT 0,
    "result_msg"       varchar(512) NULL     DEFAULT '',
    "creator"          varchar(64)  NULL     DEFAULT '',
    "create_time"      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"          varchar(64)  NULL     DEFAULT '',
    "update_time"      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"          boolean      NOT NULL DEFAULT FALSE,
    "tenant_id"        bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_api_access_log
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for infra_api_error_log
-- ----------------------------
DROP TABLE IF EXISTS "infra_api_error_log";
CREATE TABLE "infra_api_error_log"
(
    "id"                           bigint GENERATED BY DEFAULT AS IDENTITY,
    "trace_id"                     varchar(64)   NOT NULL,
    "user_id"                      bigint        NOT NULL DEFAULT 0,
    "user_type"                    smallint      NOT NULL DEFAULT 0,
    "application_name"             varchar(50)   NOT NULL,
    "request_method"               varchar(16)   NOT NULL,
    "request_url"                  varchar(255)  NOT NULL,
    "request_params"               varchar(8000) NOT NULL,
    "user_ip"                      varchar(50)   NOT NULL,
    "user_agent"                   varchar(512)  NOT NULL,
    "exception_time"               timestamp     NOT NULL,
    "exception_name"               varchar(128)  NOT NULL DEFAULT '',
    "exception_message"            text          NOT NULL,
    "exception_root_cause_message" text          NOT NULL,
    "exception_stack_trace"        text          NOT NULL,
    "exception_class_name"         varchar(512)  NOT NULL,
    "exception_file_name"          varchar(512)  NOT NULL,
    "exception_method_name"        varchar(512)  NOT NULL,
    "exception_line_number"        integer       NOT NULL,
    "process_status"               smallint      NOT NULL,
    "process_time"                 timestamp     NULL     DEFAULT NULL,
    "process_user_id"              integer       NULL     DEFAULT 0,
    "creator"                      varchar(64)   NULL     DEFAULT '',
    "create_time"                  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"                      varchar(64)   NULL     DEFAULT '',
    "update_time"                  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"                      boolean       NOT NULL DEFAULT FALSE,
    "tenant_id"                    bigint        NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_api_error_log
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for infra_codegen_column
-- ----------------------------
DROP TABLE IF EXISTS "infra_codegen_column";
CREATE TABLE "infra_codegen_column"
(
    "id"                       bigint GENERATED BY DEFAULT AS IDENTITY,
    "table_id"                 bigint       NOT NULL,
    "column_name"              varchar(200) NOT NULL,
    "data_type"                varchar(100) NOT NULL,
    "column_comment"           varchar(500) NOT NULL,
    "nullable"                 boolean      NOT NULL,
    "primary_key"              boolean      NOT NULL,
    "ordinal_position"         integer      NOT NULL,
    "java_type"                varchar(32)  NOT NULL,
    "java_field"               varchar(64)  NOT NULL,
    "dict_type"                varchar(200) NULL     DEFAULT '',
    "example"                  varchar(64)  NULL     DEFAULT NULL,
    "create_operation"         boolean      NOT NULL,
    "update_operation"         boolean      NOT NULL,
    "list_operation"           boolean      NOT NULL,
    "list_operation_condition" varchar(32)  NOT NULL DEFAULT '=',
    "list_operation_result"    boolean      NOT NULL,
    "html_type"                varchar(32)  NOT NULL,
    "creator"                  varchar(64)  NULL     DEFAULT '',
    "create_time"              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"                  varchar(64)  NULL     DEFAULT '',
    "update_time"              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"                  boolean      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_codegen_column
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for infra_codegen_table
-- ----------------------------
DROP TABLE IF EXISTS "infra_codegen_table";
CREATE TABLE "infra_codegen_table"
(
    "id"                    bigint GENERATED BY DEFAULT AS IDENTITY,
    "data_source_config_id" bigint       NOT NULL,
    "scene"                 smallint     NOT NULL DEFAULT 1,
    "table_name"            varchar(200) NOT NULL DEFAULT '',
    "table_comment"         varchar(500) NOT NULL DEFAULT '',
    "remark"                varchar(500) NULL     DEFAULT NULL,
    "module_name"           varchar(30)  NOT NULL,
    "business_name"         varchar(30)  NOT NULL,
    "class_name"            varchar(100) NOT NULL DEFAULT '',
    "class_comment"         varchar(50)  NOT NULL,
    "author"                varchar(50)  NOT NULL,
    "template_type"         smallint     NOT NULL DEFAULT 1,
    "front_type"            smallint     NOT NULL,
    "parent_menu_id"        bigint       NULL     DEFAULT NULL,
    "master_table_id"       bigint       NULL     DEFAULT NULL,
    "sub_join_column_id"    bigint       NULL     DEFAULT NULL,
    "sub_join_many"         boolean      NULL     DEFAULT NULL,
    "tree_parent_column_id" bigint       NULL     DEFAULT NULL,
    "tree_name_column_id"   bigint       NULL     DEFAULT NULL,
    "creator"               varchar(64)  NULL     DEFAULT '',
    "create_time"           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"               varchar(64)  NULL     DEFAULT '',
    "update_time"           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"               boolean      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_codegen_table
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for infra_config
-- ----------------------------
DROP TABLE IF EXISTS "infra_config";
CREATE TABLE "infra_config"
(
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "category"    varchar(50)  NOT NULL,
    "type"        smallint     NOT NULL,
    "name"        varchar(100) NOT NULL DEFAULT '',
    "config_key"  varchar(100) NOT NULL DEFAULT '',
    "value"       varchar(500) NOT NULL DEFAULT '',
    "visible"     boolean      NOT NULL,
    "remark"      varchar(500) NULL     DEFAULT NULL,
    "creator"     varchar(64)  NULL     DEFAULT '',
    "create_time" timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64)  NULL     DEFAULT '',
    "update_time" timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     boolean      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_config
-- ----------------------------
BEGIN;
INSERT INTO "infra_config" ("id", "category", "type", "name", "config_key", "value", "visible", "remark", "creator",
                            "create_time", "updater", "update_time", "deleted")
VALUES (2, 'biz', 1, '用户管理-账号初始密码', 'system.user.init-password', '123456', FALSE, '初始化密码 123456',
        'admin', '2021-01-05 17:03:48', '1', '2024-07-20 17:22:47', FALSE);
INSERT INTO "infra_config" ("id", "category", "type", "name", "config_key", "value", "visible", "remark", "creator",
                            "create_time", "updater", "update_time", "deleted")
VALUES (7, 'url', 2, 'MySQL 监控的地址', 'url.druid', '', TRUE, '', '1', '2023-04-07 13:41:16', '1',
        '2023-04-07 14:33:38', FALSE);
INSERT INTO "infra_config" ("id", "category", "type", "name", "config_key", "value", "visible", "remark", "creator",
                            "create_time", "updater", "update_time", "deleted")
VALUES (8, 'url', 2, 'SkyWalking 监控的地址', 'url.skywalking', '', TRUE, '', '1', '2023-04-07 13:41:16', '1',
        '2023-04-07 14:57:03', FALSE);
INSERT INTO "infra_config" ("id", "category", "type", "name", "config_key", "value", "visible", "remark", "creator",
                            "create_time", "updater", "update_time", "deleted")
VALUES (9, 'url', 2, 'Spring Boot Admin 监控的地址', 'url.spring-boot-admin', '', TRUE, '', '1', '2023-04-07 13:41:16',
        '1', '2023-04-07 14:52:07', FALSE);
INSERT INTO "infra_config" ("id", "category", "type", "name", "config_key", "value", "visible", "remark", "creator",
                            "create_time", "updater", "update_time", "deleted")
VALUES (10, 'url', 2, 'Swagger 接口文档的地址', 'url.swagger', '', TRUE, '', '1', '2023-04-07 13:41:16', '1',
        '2023-04-07 14:59:00', FALSE);
INSERT INTO "infra_config" ("id", "category", "type", "name", "config_key", "value", "visible", "remark", "creator",
                            "create_time", "updater", "update_time", "deleted")
VALUES (11, 'ui', 2, '腾讯地图 key', 'tencent.lbs.key', 'TVDBZ-TDILD-4ON4B-PFDZA-RNLKH-VVF6E', TRUE, '腾讯地图 key',
        '1', '2023-06-03 19:16:27', '1', '2023-06-03 19:16:27', FALSE);
INSERT INTO "infra_config" ("id", "category", "type", "name", "config_key", "value", "visible", "remark", "creator",
                            "create_time", "updater", "update_time", "deleted")
VALUES (12, 'test2', 2, 'test3', 'test4', 'test5', TRUE, 'test6', '1', '2023-12-03 09:55:16', '1',
        '2025-04-06 21:00:09', FALSE);
INSERT INTO "infra_config" ("id", "category", "type", "name", "config_key", "value", "visible", "remark", "creator",
                            "create_time", "updater", "update_time", "deleted")
VALUES (13, '用户管理-账号初始密码', 2, '用户管理-注册开关', 'system.user.register-enabled', 'true', FALSE, '', '1',
        '2025-04-26 17:23:41', '1', '2025-04-26 17:23:41', FALSE);
COMMIT;

-- ----------------------------
-- Table structure for infra_data_source_config
-- ----------------------------
DROP TABLE IF EXISTS "infra_data_source_config";
CREATE TABLE "infra_data_source_config"
(
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(100)  NOT NULL DEFAULT '',
    "url"         varchar(1024) NOT NULL,
    "username"    varchar(255)  NOT NULL,
    "password"    varchar(255)  NOT NULL DEFAULT '',
    "creator"     varchar(64)   NULL     DEFAULT '',
    "create_time" timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64)   NULL     DEFAULT '',
    "update_time" timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     boolean       NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_data_source_config
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for infra_file
-- ----------------------------
DROP TABLE IF EXISTS "infra_file";
CREATE TABLE "infra_file"
(
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "config_id"   bigint        NULL     DEFAULT NULL,
    "name"        varchar(256)  NULL     DEFAULT NULL,
    "path"        varchar(512)  NOT NULL,
    "url"         varchar(1024) NOT NULL,
    "type"        varchar(128)  NULL     DEFAULT NULL,
    "size"        integer       NOT NULL,
    "creator"     varchar(64)   NULL     DEFAULT '',
    "create_time" timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64)   NULL     DEFAULT '',
    "update_time" timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     boolean       NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_file
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for infra_file_config
-- ----------------------------
DROP TABLE IF EXISTS "infra_file_config";
CREATE TABLE "infra_file_config"
(
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(63)   NOT NULL,
    "storage"     smallint      NOT NULL,
    "remark"      varchar(255)  NULL     DEFAULT NULL,
    "master"      boolean       NOT NULL,
    "config"      varchar(4096) NOT NULL,
    "creator"     varchar(64)   NULL     DEFAULT '',
    "create_time" timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64)   NULL     DEFAULT '',
    "update_time" timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     boolean       NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_file_config
-- ----------------------------
BEGIN;
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (4, '数据库（示例）', 1, '我是数据库', FALSE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.db.DBFileClientConfig\",\"domain\":\"http://127.0.0.1:48080\"}',
        '1', '2022-03-15 23:56:24', '1', '2025-08-18 08:35:14', FALSE);
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (22, '七牛存储器（示例）', 20, '请换成你自己的密钥！！！', TRUE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.s3.S3FileClientConfig\",\"endpoint\":\"s3.cn-south-1.qiniucs.com\",\"domain\":\"http://test.yudao.iocoder.cn\",\"bucket\":\"ruoyi-vue-pro\",\"accessKey\":\"3TvrJ70gl2Gt6IBe7_IZT1F6i_k0iMuRtyEv4EyS\",\"accessSecret\":\"wd0tbVBYlp0S-ihA8Qg2hPLncoP83wyrIq24OZuY\",\"enablePathStyleAccess\":false,\"enablePublicAccess\":true}',
        '1', '2024-01-13 22:11:12', '1', '2025-08-18 08:35:14', FALSE);
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (24, '腾讯云存储（示例）', 20, '请换成你的密钥！！！', FALSE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.s3.S3FileClientConfig\",\"endpoint\":\"https://cos.ap-shanghai.myqcloud.com\",\"domain\":\"http://tengxun-oss.iocoder.cn\",\"bucket\":\"aoteman-1255880240\",\"accessKey\":\"AKIDAF6WSh1uiIjwqtrOsGSN3WryqTM6cTMt\",\"accessSecret\":\"X\",\"enablePathStyleAccess\":false,\"enablePublicAccess\":true}',
        '1', '2024-11-09 16:03:22', '1', '2025-08-18 08:35:14', FALSE);
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (25, '阿里云存储（示例）', 20, '', FALSE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.s3.S3FileClientConfig\",\"endpoint\":\"oss-cn-beijing.aliyuncs.com\",\"domain\":\"http://ali-oss.iocoder.cn\",\"bucket\":\"yunai-aoteman\",\"accessKey\":\"LTAI5tEQLgnDyjh3WpNcdMKA\",\"accessSecret\":\"X\",\"enablePathStyleAccess\":false,\"enablePublicAccess\":true}',
        '1', '2024-11-09 16:47:08', '1', '2025-08-18 08:35:14', FALSE);
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (26, '火山云存储（示例）', 20, '', FALSE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.s3.S3FileClientConfig\",\"endpoint\":\"tos-s3-cn-beijing.volces.com\",\"domain\":null,\"bucket\":\"yunai\",\"accessKey\":\"AKLTZjc3Zjc4MzZmMjU3NDk0ZTgxYmIyMmFkNTIwMDI1ZGE\",\"accessSecret\":\"X==\",\"enablePathStyleAccess\":false,\"enablePublicAccess\":true}',
        '1', '2024-11-09 16:56:42', '1', '2025-08-18 08:35:14', FALSE);
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (27, '华为云存储（示例）', 20, '', FALSE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.s3.S3FileClientConfig\",\"endpoint\":\"obs.cn-east-3.myhuaweicloud.com\",\"domain\":\"\",\"bucket\":\"yudao\",\"accessKey\":\"PVDONDEIOTW88LF8DC4U\",\"accessSecret\":\"X\",\"enablePathStyleAccess\":false}',
        '1', '2024-11-09 17:18:41', '1', '2025-08-18 08:35:14', FALSE);
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (28, 'MinIO 存储（示例）', 20, '', FALSE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.s3.S3FileClientConfig\",\"endpoint\":\"http://127.0.0.1:9000\",\"domain\":\"http://127.0.0.1:9000/yudao\",\"bucket\":\"yudao\",\"accessKey\":\"admin\",\"accessSecret\":\"password\",\"enablePathStyleAccess\":false,\"enablePublicAccess\":true}',
        '1', '2024-11-09 17:43:10', '1', '2025-08-18 08:35:14', FALSE);
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (29, '本地存储（示例）', 10, '仅适合 mac 或 windows', FALSE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.local.LocalFileClientConfig\",\"basePath\":\"/Users/yunai/tmp/file\",\"domain\":\"http://127.0.0.1:48080\"}',
        '1', '2025-05-02 11:25:45', '1', '2025-08-18 08:35:14', FALSE);
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (30, 'SFTP 存储（示例）', 12, '', FALSE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.sftp.SftpFileClientConfig\",\"basePath\":\"/upload\",\"domain\":\"http://127.0.0.1:48080\",\"host\":\"127.0.0.1\",\"port\":2222,\"username\":\"foo\",\"password\":\"pass\"}',
        '1', '2025-05-02 16:34:10', '1', '2025-08-18 08:35:14', FALSE);
INSERT INTO "infra_file_config" ("id", "name", "storage", "remark", "master", "config", "creator", "create_time",
                                 "updater", "update_time", "deleted")
VALUES (34, '七牛云存储【私有】（示例）', 20, '请换成你自己的密钥！！！', FALSE,
        '{\"@class\":\"cn.iocoder.yudao.module.infra.framework.file.core.client.s3.S3FileClientConfig\",\"endpoint\":\"s3.cn-south-1.qiniucs.com\",\"domain\":\"http://t151glocd.hn-bkt.clouddn.com\",\"bucket\":\"ruoyi-vue-pro-private\",\"accessKey\":\"3TvrJ70gl2Gt6IBe7_IZT1F6i_k0iMuRtyEv4EyS\",\"accessSecret\":\"wd0tbVBYlp0S-ihA8Qg2hPLncoP83wyrIq24OZuY\",\"enablePathStyleAccess\":false,\"enablePublicAccess\":false}',
        '1', '2025-08-17 21:22:00', '1', '2025-08-18 08:35:55', FALSE);
COMMIT;

-- ----------------------------
-- Table structure for infra_file_content
-- ----------------------------
DROP TABLE IF EXISTS "infra_file_content";
CREATE TABLE "infra_file_content"
(
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "config_id"   bigint       NOT NULL,
    "path"        varchar(512) NOT NULL,
    "content"     bytea        NOT NULL,
    "creator"     varchar(64)  NULL     DEFAULT '',
    "create_time" timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64)  NULL     DEFAULT '',
    "update_time" timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     boolean      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_file_content
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for infra_job
-- ----------------------------
DROP TABLE IF EXISTS "infra_job";
CREATE TABLE "infra_job"
(
    "id"              bigint GENERATED BY DEFAULT AS IDENTITY,
    "name"            varchar(32)  NOT NULL,
    "status"          smallint     NOT NULL,
    "handler_name"    varchar(64)  NOT NULL,
    "handler_param"   varchar(255) NULL     DEFAULT NULL,
    "cron_expression" varchar(32)  NOT NULL,
    "retry_count"     integer      NOT NULL DEFAULT 0,
    "retry_interval"  integer      NOT NULL DEFAULT 0,
    "monitor_timeout" integer      NOT NULL DEFAULT 0,
    "creator"         varchar(64)  NULL     DEFAULT '',
    "create_time"     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"         varchar(64)  NULL     DEFAULT '',
    "update_time"     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"         boolean      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_job
-- ----------------------------
BEGIN;
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (5, '支付通知 Job', 2, 'payNotifyJob', NULL, '* * * * * ?', 0, 0, 0, '1', '2021-10-27 08:34:42', '1',
        '2024-09-12 13:32:48', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (17, '支付订单同步 Job', 2, 'payOrderSyncJob', NULL, '0 0/1 * * * ?', 0, 0, 0, '1', '2023-07-22 14:36:26', '1',
        '2023-07-22 15:39:08', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (18, '支付订单过期 Job', 2, 'payOrderExpireJob', NULL, '0 0/1 * * * ?', 0, 0, 0, '1', '2023-07-22 15:36:23', '1',
        '2023-07-22 15:39:54', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (19, '退款订单的同步 Job', 2, 'payRefundSyncJob', NULL, '0 0/1 * * * ?', 0, 0, 0, '1', '2023-07-23 21:03:44',
        '1', '2023-07-23 21:09:00', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (21, '交易订单的自动过期 Job', 2, 'tradeOrderAutoCancelJob', '', '0 * * * * ?', 3, 0, 0, '1',
        '2023-09-25 23:43:26', '1', '2023-09-26 19:23:30', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (22, '交易订单的自动收货 Job', 2, 'tradeOrderAutoReceiveJob', '', '0 * * * * ?', 3, 0, 0, '1',
        '2023-09-26 19:23:53', '1', '2023-09-26 23:38:08', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (23, '交易订单的自动评论 Job', 2, 'tradeOrderAutoCommentJob', '', '0 * * * * ?', 3, 0, 0, '1',
        '2023-09-26 23:38:29', '1', '2023-09-27 11:03:10', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (24, '佣金解冻 Job', 2, 'brokerageRecordUnfreezeJob', '', '0 * * * * ?', 3, 0, 0, '1', '2023-09-28 22:01:46',
        '1', '2023-09-28 22:01:56', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (25, '访问日志清理 Job', 2, 'accessLogCleanJob', '', '0 0 0 * * ?', 3, 0, 0, '1', '2023-10-03 10:59:41', '1',
        '2023-10-03 11:01:10', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (26, '错误日志清理 Job', 2, 'errorLogCleanJob', '', '0 0 0 * * ?', 3, 0, 0, '1', '2023-10-03 11:00:43', '1',
        '2023-10-03 11:01:12', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (27, '任务日志清理 Job', 2, 'jobLogCleanJob', '', '0 0 0 * * ?', 3, 0, 0, '1', '2023-10-03 11:01:33', '1',
        '2024-09-12 13:40:34', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (33, 'demoJob', 2, 'demoJob', '', '0 * * * * ?', 1, 1, 0, '1', '2024-10-27 19:38:46', '1', '2025-05-10 18:13:54',
        FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (35, '转账订单的同步 Job', 2, 'payTransferSyncJob', '', '0 * * * * ?', 0, 0, 0, '1', '2025-05-10 17:35:54', '1',
        '2025-05-10 18:13:52', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (36, 'IoT 设备离线检查 Job', 2, 'iotDeviceOfflineCheckJob', '', '0 * * * * ?', 0, 0, 0, '1',
        '2025-07-03 23:48:44', '\"1\"', '2025-07-03 23:48:47', FALSE);
INSERT INTO "infra_job" ("id", "name", "status", "handler_name", "handler_param", "cron_expression", "retry_count",
                         "retry_interval", "monitor_timeout", "creator", "create_time", "updater", "update_time",
                         "deleted")
VALUES (37, 'IoT OTA 升级推送 Job', 2, 'iotOtaUpgradeJob', '', '0 * * * * ?', 0, 0, 0, '1', '2025-07-03 23:49:07',
        '\"1\"', '2025-07-03 23:49:13', FALSE);
COMMIT;

-- ----------------------------
-- Table structure for infra_job_log
-- ----------------------------
DROP TABLE IF EXISTS "infra_job_log";
CREATE TABLE "infra_job_log"
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "job_id"        bigint        NOT NULL,
    "handler_name"  varchar(64)   NOT NULL,
    "handler_param" varchar(255)  NULL     DEFAULT NULL,
    "execute_index" smallint      NOT NULL DEFAULT 1,
    "begin_time"    timestamp     NOT NULL,
    "end_time"      timestamp     NULL     DEFAULT NULL,
    "duration"      integer       NULL     DEFAULT NULL,
    "status"        smallint      NOT NULL,
    "result"        varchar(4000) NULL     DEFAULT '',
    "creator"       varchar(64)   NULL     DEFAULT '',
    "create_time"   timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"       varchar(64)   NULL     DEFAULT '',
    "update_time"   timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"       boolean       NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Records of infra_job_log
-- ----------------------------
BEGIN;
COMMIT;