//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use daoyi_cloud_common::constants::enumeration::Gender;
use salvo::oapi::ToSchema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// 系统用户
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "sys_user")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    /// 用户ID
    #[sea_orm(primary_key)]
    pub id: i64,
    /// 用户姓名
    pub name: String,
    /// 性别
    pub gender: Gender,
    /// 登录账号
    pub account: String,
    /// 登录密码
    pub password: String,
    /// 手机号码
    pub mobile_phone: String,
    /// 出生日期
    pub birthday: Date,
    /// 是否启用
    pub enabled: bool,
    /// 创建时间
    pub created_at: DateTime,
    /// 更新时间
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
